# Generated by Django 3.1.4 on 2020-12-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201113_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hits',
            field=models.SmallIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
