# Generated by Django 3.1.4 on 2020-12-21 19:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20201221_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterField(
            model_name='post',
            name='full_text',
            field=ckeditor.fields.RichTextField(verbose_name='Полный текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=ckeditor.fields.RichTextField(verbose_name='Краткое описание'),
        ),
    ]
