# Generated by Django 3.1.2 on 2020-10-22 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Учебный год')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_name', models.CharField(max_length=100, verbose_name='Название дисциплины')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.CharField(max_length=50, verbose_name='Электронная почта')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=20, verbose_name='Название класса')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('class_ruk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ktp.teacher', verbose_name='Классный руководитель')),
            ],
        ),
        migrations.CreateModel(
            name='KTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_lesson', models.SmallIntegerField()),
                ('plan_date', models.DateField(blank=True, verbose_name='Планируемая дата')),
                ('fact_date', models.DateField(blank=True, verbose_name='Дата проведения')),
                ('theme', models.TextField(verbose_name='Тема урока')),
                ('home_task', models.CharField(max_length=255, verbose_name='Домашнее задание')),
                ('created_at', models.DateField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ktp.academicyear', verbose_name='Учебный год')),
                ('discipline_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ktp.discipline', verbose_name='Дисциплина')),
                ('school_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ktp.schoolform', verbose_name='Класс')),
            ],
        ),
    ]
