# Generated by Django 3.1.2 on 2020-10-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktp', '0002_auto_20201022_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
    ]
