# Generated by Django 3.1.2 on 2020-10-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktp', '0003_auto_20201022_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='ktp',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
