# Generated by Django 3.1.2 on 2020-10-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktp', '0004_ktp_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ktp',
            name='fact_date',
            field=models.DateField(null=True, verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='ktp',
            name='home_task',
            field=models.CharField(max_length=255, null=True, verbose_name='Домашнее задание'),
        ),
    ]
