# Generated by Django 3.1.3 on 2020-11-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktp', '0005_auto_20201023_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ktp',
            options={'ordering': ('number_of_lesson',), 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterField(
            model_name='ktp',
            name='fact_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='ktp',
            name='home_task',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Домашнее задание'),
        ),
        migrations.AlterField(
            model_name='ktp',
            name='number_of_lesson',
            field=models.SmallIntegerField(verbose_name='Номер урока'),
        ),
    ]
