# Generated by Django 3.1.3 on 2020-11-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiaTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.TextField(verbose_name='Текст задания')),
                ('exam', models.IntegerField(choices=[(1, 'Ege'), (2, 'Oge')], default=1, verbose_name='Тип экзамена')),
                ('task_number', models.SmallIntegerField(verbose_name='Номер задания')),
                ('file_with_solition', models.CharField(max_length=40, null=True, verbose_name='Файл с решением')),
                ('comments', models.TextField(null=True, verbose_name='Комментарии')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
