# Generated by Django 3.1.4 on 2020-12-13 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gia', '0003_auto_20201116_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Экзамен')),
                ('slug', models.CharField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Экзамен',
                'verbose_name_plural': 'Экзамены',
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.SmallIntegerField(verbose_name='Номер задания')),
                ('slug', models.CharField(blank=True, max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание задания')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gia.exam', verbose_name='Тип экзамена')),
            ],
            options={
                'verbose_name': 'Тип задания',
                'verbose_name_plural': 'Типы задания',
            },
        ),
    ]
