# Generated by Django 3.1.4 on 2020-12-16 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gia', '0005_auto_20201213_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giatask',
            old_name='file_with_solition',
            new_name='file_with_solution',
        ),
        migrations.RemoveField(
            model_name='giatask',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='giatask',
            name='task_number',
        ),
    ]
