# Generated by Django 3.1.4 on 2020-12-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postblog',
            name='hits',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
