# Generated by Django 3.1.4 on 2020-12-21 19:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201221_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='full_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Полный текст поста'),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='intro',
            field=ckeditor.fields.RichTextField(verbose_name='Краткое описание поста'),
        ),
    ]
