# Generated by Django 3.1.5 on 2021-01-11 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_type', models.CharField(max_length=40, unique=True, verbose_name='Тип тренажёра')),
                ('name', models.CharField(max_length=100, verbose_name='Название тренажёра')),
                ('short_instruction', models.CharField(blank=True, max_length=100, null=True, verbose_name='Краткая инструкция')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание тренажёра')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тренажёр',
                'verbose_name_plural': 'Тренажёры',
            },
        ),
        migrations.CreateModel(
            name='UserPerformTrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('total_tasks', models.SmallIntegerField()),
                ('level_achieved', models.SmallIntegerField(default=1)),
                ('correct_perf_tasks', models.SmallIntegerField()),
                ('data', models.JSONField()),
                ('train_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.train')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
