# Generated by Django 3.1.5 on 2021-01-11 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_auto_20210111_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userperformtrain',
            old_name='train_id',
            new_name='train',
        ),
        migrations.RenameField(
            model_name='userperformtrain',
            old_name='user_id',
            new_name='user',
        ),
    ]
